"""Metadados dos configuradores/cotações PC gamer no Brasil."""

from __future__ import annotations

from typing import Any

# Ordem de slots alinhada ao wizard Pichau + extras nossos (cooler AIO, suporte VGA)
BUILD_WIZARD_STEPS: list[dict[str, Any]] = [
    {
        "order": 1,
        "slug": "processador",
        "label": "Processador",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
    },
    {
        "order": 2,
        "slug": "motherboard",
        "label": "Placa-mãe",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
        "brands_hint": ("asus", "gigabyte", "msi", "asrock"),
    },
    {
        "order": 3,
        "slug": "memoria_ddr5",
        "label": "Memória RAM DDR5",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
    },
    {
        "order": 4,
        "slug": "placa_video",
        "label": "Placa de vídeo",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
    },
    {
        "order": 5,
        "slug": "nvme",
        "label": "SSD NVMe",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
    },
    {
        "order": 6,
        "slug": "gabinete",
        "label": "Gabinete",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
    },
    {
        "order": 7,
        "slug": "fonte",
        "label": "Fonte de alimentação",
        "pichau": True,
        "kabum": True,
        "terabyte": True,
        "required": True,
    },
    {
        "order": 8,
        "slug": "water_cooler",
        "label": "Water cooler / cooler CPU",
        "pichau": "cooler do processador",
        "kabum": True,
        "terabyte": True,
        "required": False,
    },
    {
        "order": 9,
        "slug": "fan",
        "label": "Fans adicionais",
        "pichau": False,
        "kabum": True,
        "terabyte": True,
        "required": False,
    },
    {
        "order": 10,
        "slug": "suporte_vga",
        "label": "Suporte / bracket VGA",
        "pichau": False,
        "kabum": False,
        "terabyte": False,
        "required": False,
    },
]

# Excluídos do nosso escopo (presentes em Pichau/Terabyte como periféricos)
EXCLUDED_CATEGORIES = (
    "monitor",
    "teclado",
    "mouse",
    "headset",
    "webcam",
    "perifericos",
)

REFERENCE_SITES: list[dict[str, Any]] = [
    {
        "slug": "meupc",
        "name": "MEUPC.NET",
        "url": "https://meupc.net/build",
        "type": "agregador",
        "use_for": "Comparar menor preço entre lojas; ~24k peças; histórico 90 dias",
        "compatibility": ["soquete", "chipset", "ram", "formato_placa"],
        "limitations": ["Não valida slots M.2 em detalhe"],
    },
    {
        "slug": "kabum",
        "name": "KaBuM! Monte seu PC",
        "url": "https://www.kabum.com.br/monte-seu-pc",
        "type": "loja",
        "use_for": "Cotação single-store + opção montagem Customiza (OCCT)",
        "compatibility": ["soquete", "chipset", "ram", "gabinete", "watt_fonte"],
        "montagem": "Parceiro Customiza; teste OCCT; ES",
    },
    {
        "slug": "pichau",
        "name": "Pichau Monte seu PC",
        "url": "https://www.pichau.com.br/monte-seu-pc",
        "type": "loja",
        "use_for": "Wizard clássico; custo-benefício; marcas Mancer/TGT",
        "compatibility": ["filtro por passo"],
        "montagem": "Config personalizada via ferramenta NÃO é enviada montada",
    },
    {
        "slug": "terabyte",
        "name": "Terabyteshop Full Custom",
        "url": "https://www.terabyteshop.com.br/pc-gamer/full-custom",
        "type": "loja",
        "use_for": "Máxima liberdade por plataforma (AM5, LGA1700, etc.)",
        "compatibility": ["plataforma primeiro", "alerta incompatibilidade"],
        "montagem": "Montado e certificado; frete grátis em builds",
    },
    {
        "slug": "rocketz",
        "name": "Rocketz Monte seu PC",
        "url": "https://rocketz.com.br/monte-seu-pc",
        "type": "loja",
        "use_for": "UX visual gabinete + total atualizado em tempo real",
        "compatibility": ["guiado por objetivo: jogos/trabalho/stream"],
    },
    {
        "slug": "studiopc",
        "name": "StudioPC",
        "url": "https://www.studiopc.com.br",
        "type": "pre_montado",
        "use_for": "Referência de tiers (Supreme, etc.) e opcionais",
        "compatibility": ["configs fechadas com upgrades opcionais"],
    },
    {
        "slug": "pcbuilder",
        "name": "PC Builder (Moema)",
        "url": "https://pcbuilder.com.br/build-personalizada",
        "type": "servico",
        "use_for": "Modelo consultivo: orçamento 24h + montagem peças cliente",
        "montagem": "A partir R$549 com peças do cliente; grátis na build completa",
    },
    {
        "slug": "4gamers",
        "name": "4Gamers",
        "url": "https://www.4gamers.com.br/monte-seu-computador",
        "type": "loja",
        "use_for": "Monte seu computador + linhas Starter→Colosseum (SP, envio BR)",
        "compatibility": [
            "processador",
            "placa_mae",
            "ram",
            "gpu",
            "armazenamento",
            "gabinete",
            "fonte",
            "cooler",
        ],
        "montagem": "PC customizável; tiers por faixa de preço",
    },
    {
        "slug": "mercadolivre",
        "name": "Mercado Livre",
        "url": "https://www.mercadolivre.com.br",
        "type": "marketplace",
        "use_for": "Automação via API MLB/search — comparar usados e novos",
        "compatibility": [],
    },
    {
        "slug": "aliexpress",
        "name": "AliExpress",
        "url": "https://pt.aliexpress.com",
        "type": "marketplace",
        "use_for": "Importação — API afiliados ou busca wholesale",
        "compatibility": [],
        "notes": "Prazo de entrega + impostos não incluídos na cotação automática",
    },
]

# Regras de compatibilidade inspiradas KaBuM/Terabyte (validação futura)
COMPAT_RULES_AMD_AM5: dict[str, Any] = {
    "platform": "amd_am5",
    "socket": "AM5",
    "memory_type": "DDR5",
    "motherboard_chipsets": ("A620", "B650", "B850", "X670", "X870"),
    "psu_headroom_percent": 25,
    "min_ram_gb_gamer": 16,
    "recommended_ram_gb": 32,
}
