#!/bin/bash
# FGSRV06 Mono Warning Fix Script
# Generated by Hive Mind Collective

set -e

echo "======================================"
echo "FGSRV06 Mono Warning Resolution Script"
echo "======================================"

# Function to fix mono warnings
fix_mono_warnings() {
    echo "→ Checking for existing mono repositories..."

    # Remove problematic mono repositories
    if ls /etc/apt/sources.list.d/*mono* 2>/dev/null; then
        echo "  Found mono repository files, removing..."
        sudo rm -f /etc/apt/sources.list.d/*mono*
    fi

    # Remove old mono GPG keys
    echo "→ Cleaning up GPG keys..."
    sudo apt-key list 2>/dev/null | grep -i mono && {
        echo "  Note: Manual GPG key removal may be needed"
    }

    # Update package lists
    echo "→ Updating package lists..."
    sudo apt update

    # Check for mono warnings
    echo "→ Testing apt upgrade..."
    if sudo apt upgrade -y 2>&1 | tee /tmp/apt_upgrade.log | grep -i mono; then
        echo "⚠️  Mono-related messages detected. Checking details..."

        # If mono-devel or similar packages cause issues
        if grep -q "mono-devel\|mono-complete" /tmp/apt_upgrade.log; then
            echo "→ Attempting to fix mono package dependencies..."
            sudo apt --fix-broken install -y
            sudo apt autoremove -y
        fi
    else
        echo "✅ No mono warnings detected!"
    fi

    # Final verification
    echo "→ Final verification..."
    if sudo apt upgrade -s | grep -i "warning.*mono"; then
        echo "⚠️  Some mono warnings persist. Manual intervention may be needed."
        return 1
    else
        echo "✅ apt upgrade runs clean - no mono warnings!"
        return 0
    fi
}

# Main execution
main() {
    echo "Starting mono warning resolution..."
    echo ""

    if fix_mono_warnings; then
        echo ""
        echo "✅ SUCCESS: Mono warnings have been resolved!"
        echo "System is ready for clean apt upgrade."
    else
        echo ""
        echo "⚠️  Some issues remain. Suggested manual steps:"
        echo "  1. Check /etc/apt/sources.list.d/ for mono files"
        echo "  2. Review apt policy: apt-cache policy | grep mono"
        echo "  3. Check for held packages: apt-mark showhold"
        echo "  4. Consider: sudo dpkg --configure -a"
    fi
}

# Run main function
main

echo ""
echo "Script execution complete."
echo "Log saved to: /tmp/apt_upgrade.log"