module.exports = {
  testEnvironment: 'node',
  coverageDirectory: 'coverage',
  setupFilesAfterEnv: ['<rootDir>/tests/setup.js'],
  collectCoverage: true,
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  collectCoverageFrom: [
    'src/greeting/**/*.js',
    'src/dashboard/**/*.js',
    '!**/node_modules/**',
    '!**/vendor/**',
  ],
  testMatch: ['**/tests/**/*.test.js', '**/tests/**/*.spec.js'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/src/vendor/',
    '/src/node_modules/',
    '/src/html/',
    '/src/app/',
  ],
  modulePathIgnorePatterns: [
    '/src/vendor/',
    '/src/node_modules/',
    '/src/html/',
    '/src/app/',
    '/src/bootstrap/',
    '/src/config/',
    '/src/database/',
    '/src/public/',
  ],
  transformIgnorePatterns: ['/node_modules/', '/src/vendor/'],
  cacheDirectory: '/tmp/jest-cache-agl-hostman',
  maxWorkers: 1,
  verbose: true,
  testTimeout: 30000,
};
