// Patch OpenClaw — LiteLLM central CT186 (substituir localhost pelo URL em openclaw-litellm-ct186.jq se necessário)
.models.providers.zai.baseUrl = "http://100.125.249.8:4000" |
.models.providers.zai.apiKey = "sk-litellm-default" |
.models.providers.zai.api = "openai-completions" |
.models.providers.anthropic.baseUrl = "http://100.125.249.8:4000" |
.models.providers.anthropic.apiKey = "sk-litellm-default" |
.models.providers.deepseek.baseUrl = "http://100.125.249.8:4000" |
.models.providers.deepseek.apiKey = "sk-litellm-default" |
.models.providers.google.baseUrl = "http://100.125.249.8:4000" |
.models.providers.google.apiKey = "sk-litellm-default" |
.models.providers.openai.baseUrl = "http://100.125.249.8:4000" |
.models.providers.openai.apiKey = "sk-litellm-default" |
.models.providers.kimi.baseUrl = "http://100.125.249.8:4000" |
.models.providers.kimi.apiKey = "sk-litellm-default" |
.models.providers.moonshot.baseUrl = "http://100.125.249.8:4000" |
.models.providers.moonshot.apiKey = "sk-litellm-default" |
.models.providers.qwen.baseUrl = "http://100.125.249.8:4000" |
.models.providers.qwen.apiKey = "sk-litellm-default" |
.models.providers.openrouter.baseUrl = "http://100.125.249.8:4000" |
.models.providers.openrouter.apiKey = "sk-litellm-default" |
.models.providers.dashscope.baseUrl = "http://100.125.249.8:4000" |
.models.providers.dashscope.apiKey = "sk-litellm-default" |
.models.providers.dashscope.api = "openai-completions"
