#!/bin/bash
#
# Harbor CT182 CI/CD Integration Script
# Configure Harbor for GitLab CI, GitHub Actions, Jenkins
#
# Author: Hive Mind Coder Agent
# Session: swarm-1761131660305-65la2tiid
# Date: 2025-10-22
# Version: 1.0.0
#

set -euo pipefail

# Configuration
HARBOR_URL="${HARBOR_URL:-https://harbor.yourdomain.com}"
HARBOR_ADMIN="${HARBOR_ADMIN:-admin}"
HARBOR_PASSWORD="${HARBOR_PASSWORD}"
PROJECT_NAME="${PROJECT_NAME:-library}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[✗]${NC} $*"; exit 1; }

echo -e "\n${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Harbor CT182 CI/CD Integration Setup                 ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}\n"

# Create Robot Account for CI/CD
create_robot_account() {
    local robot_name="$1"
    local project_name="$2"

    echo -e "\n${BLUE}═══ Creating Robot Account: $robot_name ═══${NC}\n"

    info "Robot accounts provide secure authentication for CI/CD pipelines"

    # Robot account configuration
    cat > "/tmp/robot-${robot_name}.json" << EOF
{
  "name": "${robot_name}",
  "description": "CI/CD robot account for ${project_name}",
  "duration": -1,
  "level": "project",
  "permissions": [
    {
      "kind": "project",
      "namespace": "${project_name}",
      "access": [
        {"resource": "repository", "action": "push"},
        {"resource": "repository", "action": "pull"},
        {"resource": "artifact", "action": "delete"}
      ]
    }
  ]
}
EOF

    info "Robot account configuration created"
    info "Create this robot via Harbor Web UI:"
    echo "  1. Navigate to Projects → ${project_name} → Robot Accounts"
    echo "  2. Click 'New Robot Account'"
    echo "  3. Name: ${robot_name}"
    echo "  4. Duration: Never Expires"
    echo "  5. Permissions: Push, Pull, Delete artifacts"
    echo "  6. Save credentials securely"

    warn "Manual step required: Create robot account via Harbor UI"
}

# Generate GitLab CI Configuration
generate_gitlab_ci() {
    echo -e "\n${BLUE}═══ Generating GitLab CI Configuration ═══${NC}\n"

    cat > ".gitlab-ci.yml" << 'EOF'
# GitLab CI/CD Configuration for Harbor CT182
# Generated by Harbor CT182 CI/CD Integration Script

variables:
  HARBOR_REGISTRY: harbor.yourdomain.com
  HARBOR_PROJECT: library
  IMAGE_NAME: $HARBOR_REGISTRY/$HARBOR_PROJECT/$CI_PROJECT_NAME
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

stages:
  - build
  - scan
  - push
  - deploy

# Build Docker Image
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker save $IMAGE_NAME:$IMAGE_TAG > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 1 hour

# Security Scan
security_scan:
  stage: scan
  image: aquasec/trivy:latest
  script:
    - docker load < image.tar
    - trivy image --severity HIGH,CRITICAL --exit-code 1 $IMAGE_NAME:$IMAGE_TAG
  dependencies:
    - build
  allow_failure: false

# Push to Harbor
push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login $HARBOR_REGISTRY -u $HARBOR_ROBOT_USER -p $HARBOR_ROBOT_PASSWORD
  script:
    - docker load < image.tar
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  dependencies:
    - build
    - security_scan
  only:
    - main
    - develop

# Deploy (Example)
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl set image deployment/myapp myapp=$IMAGE_NAME:$IMAGE_TAG
  only:
    - main
  when: manual

# Required CI/CD Variables (Settings → CI/CD → Variables):
# - HARBOR_ROBOT_USER: robot$gitlab-ci
# - HARBOR_ROBOT_PASSWORD: [robot account password]
EOF

    success "GitLab CI configuration generated: .gitlab-ci.yml"

    info "Required GitLab CI/CD variables:"
    echo "  HARBOR_ROBOT_USER = robot\$gitlab-ci"
    echo "  HARBOR_ROBOT_PASSWORD = [robot account password]"
}

# Generate GitHub Actions Configuration
generate_github_actions() {
    echo -e "\n${BLUE}═══ Generating GitHub Actions Configuration ═══${NC}\n"

    mkdir -p ".github/workflows"

    cat > ".github/workflows/harbor-deploy.yml" << 'EOF'
# GitHub Actions Workflow for Harbor CT182
# Generated by Harbor CT182 CI/CD Integration Script

name: Build and Push to Harbor

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  HARBOR_REGISTRY: harbor.yourdomain.com
  HARBOR_PROJECT: library
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_ROBOT_USER }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.HARBOR_REGISTRY }}/${{ env.HARBOR_PROJECT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

# Required GitHub Secrets (Settings → Secrets → Actions):
# - HARBOR_ROBOT_USER: robot$github-actions
# - HARBOR_ROBOT_PASSWORD: [robot account password]
EOF

    success "GitHub Actions workflow generated: .github/workflows/harbor-deploy.yml"

    info "Required GitHub Secrets:"
    echo "  HARBOR_ROBOT_USER = robot\$github-actions"
    echo "  HARBOR_ROBOT_PASSWORD = [robot account password]"
}

# Generate Jenkins Pipeline
generate_jenkins_pipeline() {
    echo -e "\n${BLUE}═══ Generating Jenkins Pipeline Configuration ═══${NC}\n"

    cat > "Jenkinsfile" << 'EOF'
// Jenkins Pipeline for Harbor CT182
// Generated by Harbor CT182 CI/CD Integration Script

pipeline {
    agent any

    environment {
        HARBOR_REGISTRY = 'harbor.yourdomain.com'
        HARBOR_PROJECT = 'library'
        HARBOR_CREDENTIALS = credentials('harbor-robot-credentials')
        IMAGE_NAME = "${HARBOR_REGISTRY}/${HARBOR_PROJECT}/${JOB_NAME}"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                    docker.build("${IMAGE_NAME}:latest")
                }
            }
        }

        stage('Security Scan') {
            steps {
                script {
                    sh """
                        docker run --rm \
                            -v /var/run/docker.sock:/var/run/docker.sock \
                            aquasec/trivy:latest image \
                            --severity HIGH,CRITICAL \
                            --exit-code 1 \
                            ${IMAGE_NAME}:${IMAGE_TAG}
                    """
                }
            }
        }

        stage('Push to Harbor') {
            steps {
                script {
                    docker.withRegistry("https://${HARBOR_REGISTRY}", 'harbor-robot-credentials') {
                        docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
                        docker.image("${IMAGE_NAME}:latest").push()
                    }
                }
            }
        }

        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                script {
                    // Add deployment steps here
                    echo "Deploying ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo "Pipeline completed successfully"
        }
        failure {
            echo "Pipeline failed"
        }
    }
}

/* Required Jenkins Credentials:
 * ID: harbor-robot-credentials
 * Type: Username with password
 * Username: robot$jenkins
 * Password: [robot account password]
 */
EOF

    success "Jenkins pipeline generated: Jenkinsfile"

    info "Required Jenkins credentials:"
    echo "  ID: harbor-robot-credentials"
    echo "  Type: Username with password"
    echo "  Username: robot\$jenkins"
    echo "  Password: [robot account password]"
}

# Generate Docker Client Configuration
generate_docker_client_config() {
    echo -e "\n${BLUE}═══ Generating Docker Client Configuration ═══${NC}\n"

    cat > "docker-harbor-config.sh" << 'EOF'
#!/bin/bash
# Docker Client Configuration for Harbor CT182

HARBOR_URL="harbor.yourdomain.com"
ROBOT_USER="robot\$cicd-pipeline"
ROBOT_PASSWORD="[ROBOT_PASSWORD_HERE]"

# Login to Harbor
echo "$ROBOT_PASSWORD" | docker login "$HARBOR_URL" -u "$ROBOT_USER" --password-stdin

# Verify login
if [ $? -eq 0 ]; then
    echo "Successfully logged in to Harbor"
else
    echo "Login failed"
    exit 1
fi

# Build and push example
# docker build -t $HARBOR_URL/library/myapp:v1.0 .
# docker push $HARBOR_URL/library/myapp:v1.0
EOF

    chmod +x docker-harbor-config.sh
    success "Docker client configuration generated: docker-harbor-config.sh"
}

# Generate Kubernetes Integration
generate_kubernetes_config() {
    echo -e "\n${BLUE}═══ Generating Kubernetes Integration ═══${NC}\n"

    cat > "harbor-k8s-secret.yaml" << 'EOF'
# Kubernetes Secret for Harbor Registry
# Generated by Harbor CT182 CI/CD Integration Script

apiVersion: v1
kind: Secret
metadata:
  name: harbor-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: [BASE64_ENCODED_DOCKER_CONFIG]

---
# Usage in Pod/Deployment:
# spec:
#   imagePullSecrets:
#     - name: harbor-registry-secret
#   containers:
#     - name: myapp
#       image: harbor.yourdomain.com/library/myapp:latest
EOF

    cat > "create-k8s-secret.sh" << 'EOF'
#!/bin/bash
# Create Kubernetes Secret for Harbor

HARBOR_URL="harbor.yourdomain.com"
ROBOT_USER="robot\$kubernetes"
ROBOT_PASSWORD="[ROBOT_PASSWORD_HERE]"
NAMESPACE="default"

kubectl create secret docker-registry harbor-registry-secret \
    --docker-server="$HARBOR_URL" \
    --docker-username="$ROBOT_USER" \
    --docker-password="$ROBOT_PASSWORD" \
    --namespace="$NAMESPACE"

echo "Kubernetes secret created successfully"
EOF

    chmod +x create-k8s-secret.sh

    success "Kubernetes configuration generated"
    info "Files created:"
    echo "  - harbor-k8s-secret.yaml"
    echo "  - create-k8s-secret.sh"
}

# Generate Webhook Configuration
generate_webhook_config() {
    echo -e "\n${BLUE}═══ Webhook Integration Guide ═══${NC}\n"

    cat > "harbor-webhook-config.md" << 'EOF'
# Harbor Webhook Configuration

Harbor supports webhooks for various events to integrate with external systems.

## Supported Events

- **PUSH_ARTIFACT**: Image pushed to repository
- **PULL_ARTIFACT**: Image pulled from repository
- **DELETE_ARTIFACT**: Image deleted
- **SCANNING_COMPLETED**: Vulnerability scan completed
- **SCANNING_FAILED**: Vulnerability scan failed
- **QUOTA_EXCEED**: Storage quota exceeded
- **REPLICATION_SUCCESS**: Replication completed successfully
- **REPLICATION_FAILURE**: Replication failed

## Configuration Steps

1. Navigate to Harbor UI
2. Go to Projects → [Your Project] → Webhooks
3. Click "New Webhook"
4. Configure:
   - Name: descriptive name
   - Notify Type: http, Slack, or other supported types
   - Event Types: select events to monitor
   - Endpoint URL: your webhook receiver URL

## Example Webhook Payload

```json
{
  "type": "PUSH_ARTIFACT",
  "occur_at": 1234567890,
  "operator": "admin",
  "event_data": {
    "resources": [{
      "resource_url": "harbor.yourdomain.com/library/myapp:v1.0"
    }],
    "repository": {
      "name": "library/myapp"
    }
  }
}
```

## Slack Integration Example

```
Webhook URL: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
Event Types: PUSH_ARTIFACT, SCANNING_COMPLETED
```

## Custom Webhook Receiver (Python)

```python
from flask import Flask, request
app = Flask(__name__)

@app.route('/harbor-webhook', methods=['POST'])
def harbor_webhook():
    payload = request.json
    event_type = payload.get('type')

    if event_type == 'PUSH_ARTIFACT':
        # Handle image push event
        print(f"Image pushed: {payload['event_data']['resources'][0]['resource_url']}")

    return '', 200

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
```
EOF

    success "Webhook configuration guide generated: harbor-webhook-config.md"
}

# Main Execution
main() {
    if [[ -z "$HARBOR_PASSWORD" ]]; then
        error "HARBOR_PASSWORD environment variable must be set"
    fi

    info "Generating CI/CD integration configurations for Harbor CT182"

    create_robot_account "gitlab-ci" "$PROJECT_NAME"
    create_robot_account "github-actions" "$PROJECT_NAME"
    create_robot_account "jenkins" "$PROJECT_NAME"
    create_robot_account "kubernetes" "$PROJECT_NAME"

    generate_gitlab_ci
    generate_github_actions
    generate_jenkins_pipeline
    generate_docker_client_config
    generate_kubernetes_config
    generate_webhook_config

    echo -e "\n${GREEN}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}     CI/CD Integration Configuration Completed            ${NC}"
    echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}\n"

    echo -e "${BLUE}Generated Files:${NC}"
    echo "  ✓ .gitlab-ci.yml - GitLab CI/CD pipeline"
    echo "  ✓ .github/workflows/harbor-deploy.yml - GitHub Actions workflow"
    echo "  ✓ Jenkinsfile - Jenkins pipeline"
    echo "  ✓ docker-harbor-config.sh - Docker client configuration"
    echo "  ✓ harbor-k8s-secret.yaml - Kubernetes secret template"
    echo "  ✓ create-k8s-secret.sh - Kubernetes secret creation script"
    echo "  ✓ harbor-webhook-config.md - Webhook configuration guide"
    echo ""

    echo -e "${YELLOW}Next Steps:${NC}"
    echo "  1. Create robot accounts in Harbor UI for each CI/CD system"
    echo "  2. Configure CI/CD secrets with robot account credentials"
    echo "  3. Update HARBOR_REGISTRY and HARBOR_PROJECT variables"
    echo "  4. Test pipeline with a sample project"
    echo "  5. Configure webhooks for notifications (optional)"
    echo ""

    success "CI/CD integration setup complete!"
}

# Run main function
main "$@"
