#!/bin/bash
#
# Harbor CT182 Security Hardening Script
# Implements production-grade security controls
#
# Author: Hive Mind Coder Agent
# Session: swarm-1761131660305-65la2tiid
# Date: 2025-10-22
# Version: 1.0.0
#

set -euo pipefail

# Configuration
CT_ID="${CT_ID:-182}"
HARBOR_FQDN="${HARBOR_FQDN:-harbor.yourdomain.com}"
DATA_VOLUME="${DATA_VOLUME:-/data/registry}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[✗]${NC} $*"; }

echo -e "\n${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Harbor CT182 Security Hardening Script               ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}\n"

# 1. Firewall Configuration
configure_firewall() {
    echo -e "\n${BLUE}═══ Configuring Firewall Rules ═══${NC}\n"

    pct exec "$CT_ID" -- bash <<'EOF'
        set -e

        # Install iptables-persistent
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y iptables-persistent

        # Flush existing rules
        iptables -F
        iptables -X

        # Default policies
        iptables -P INPUT DROP
        iptables -P FORWARD DROP
        iptables -P OUTPUT ACCEPT

        # Allow loopback
        iptables -A INPUT -i lo -j ACCEPT
        iptables -A OUTPUT -o lo -j ACCEPT

        # Allow established connections
        iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

        # Allow SSH (port 22)
        iptables -A INPUT -p tcp --dport 22 -j ACCEPT

        # Allow HTTP (port 80) - redirect to HTTPS
        iptables -A INPUT -p tcp --dport 80 -j ACCEPT

        # Allow HTTPS (port 443)
        iptables -A INPUT -p tcp --dport 443 -j ACCEPT

        # Allow Docker Content Trust/Notary (port 4443) - if enabled
        # iptables -A INPUT -p tcp --dport 4443 -j ACCEPT

        # Allow ping (ICMP)
        iptables -A INPUT -p icmp --icmp-type echo-request -j ACCEPT

        # Log dropped packets (debugging)
        iptables -A INPUT -j LOG --log-prefix "IPTables-Dropped: " --log-level 4

        # Save rules
        netfilter-persistent save

        # Verify rules
        iptables -L -n -v
EOF

    success "Firewall configured with restrictive rules"
}

# 2. SSL/TLS Security
harden_ssl_tls() {
    echo -e "\n${BLUE}═══ Hardening SSL/TLS Configuration ═══${NC}\n"

    pct exec "$CT_ID" -- bash -c "
        set -e
        cd /root/harbor

        # Create custom Nginx SSL configuration
        cat > /root/harbor/common/config/nginx/ssl.conf << 'EOFNGINX'
# Strong SSL/TLS Configuration for Harbor
# Generated by Harbor CT182 Security Hardening Script

# Protocols - TLS 1.2 and 1.3 only
ssl_protocols TLSv1.2 TLSv1.3;

# Strong cipher suites
ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';

# Server cipher preference
ssl_prefer_server_ciphers on;

# SSL session cache
ssl_session_cache shared:SSL:50m;
ssl_session_timeout 1d;

# SSL session tickets disabled (for perfect forward secrecy)
ssl_session_tickets off;

# OCSP stapling
ssl_stapling on;
ssl_stapling_verify on;

# HSTS (HTTP Strict Transport Security)
add_header Strict-Transport-Security \"max-age=63072000; includeSubDomains; preload\" always;

# Security headers
add_header X-Frame-Options \"SAMEORIGIN\" always;
add_header X-Content-Type-Options \"nosniff\" always;
add_header X-XSS-Protection \"1; mode=block\" always;
add_header Referrer-Policy \"no-referrer-when-downgrade\" always;
add_header Content-Security-Policy \"default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'self';\" always;

# Disable server tokens (hide Nginx version)
server_tokens off;
EOFNGINX

        # Restart Nginx container to apply changes
        docker compose restart nginx
    "

    success "SSL/TLS security hardened"
}

# 3. Docker Security
harden_docker() {
    echo -e "\n${BLUE}═══ Hardening Docker Daemon ═══${NC}\n"

    pct exec "$CT_ID" -- bash <<'EOF'
        set -e

        # Create Docker daemon configuration
        mkdir -p /etc/docker

        cat > /etc/docker/daemon.json << 'EOFDOCKER'
{
  "icc": false,
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "live-restore": true,
  "userland-proxy": false,
  "no-new-privileges": true,
  "userns-remap": "default"
}
EOFDOCKER

        # Restart Docker to apply changes
        systemctl restart docker

        # Verify configuration
        docker info | grep -A 5 "Security"
EOF

    success "Docker daemon hardened"
}

# 4. File System Permissions
harden_filesystem() {
    echo -e "\n${BLUE}═══ Hardening File System Permissions ═══${NC}\n"

    pct exec "$CT_ID" -- bash -c "
        set -e

        # Secure Harbor configuration files
        chmod 600 /root/harbor/harbor.yml
        chown root:root /root/harbor/harbor.yml

        # Secure SSL certificates
        chmod 600 ${DATA_VOLUME}/secrets/cert/server.key
        chmod 644 ${DATA_VOLUME}/secrets/cert/server.crt
        chown -R 10000:10000 ${DATA_VOLUME}/secrets

        # Secure data directories
        chmod 755 ${DATA_VOLUME}
        chmod 700 ${DATA_VOLUME}/database
        chmod 700 ${DATA_VOLUME}/secrets

        # Secure log files
        chmod 755 /var/log/harbor

        # Remove world-readable permissions
        find ${DATA_VOLUME} -type f -perm /o+r -exec chmod o-r {} \;
        find ${DATA_VOLUME} -type d -perm /o+x -exec chmod o-x {} \;
    "

    success "File system permissions secured"
}

# 5. System Hardening
harden_system() {
    echo -e "\n${BLUE}═══ System Hardening ═══${NC}\n"

    pct exec "$CT_ID" -- bash <<'EOF'
        set -e

        # Disable unnecessary services
        systemctl disable bluetooth || true
        systemctl disable cups || true

        # Configure sysctl security parameters
        cat >> /etc/sysctl.conf << 'EOFSYSCTL'

# Harbor CT182 Security Hardening
# IP forwarding disabled (not needed for Harbor)
net.ipv4.ip_forward=0

# SYN flood protection
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_max_syn_backlog=2048
net.ipv4.tcp_synack_retries=2

# IP spoofing protection
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1

# ICMP redirect protection
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.default.secure_redirects=0

# Ignore ICMP ping requests (optional - uncomment to enable)
# net.ipv4.icmp_echo_ignore_all=1

# Log suspicious packets
net.ipv4.conf.all.log_martians=1
net.ipv4.conf.default.log_martians=1

# Disable source packet routing
net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.default.accept_source_route=0

# Kernel hardening
kernel.dmesg_restrict=1
kernel.kptr_restrict=2

# File system hardening
fs.protected_hardlinks=1
fs.protected_symlinks=1
EOFSYSCTL

        # Apply sysctl changes
        sysctl -p
EOF

    success "System hardened with security parameters"
}

# 6. Audit Logging
configure_audit_logging() {
    echo -e "\n${BLUE}═══ Configuring Audit Logging ═══${NC}\n"

    pct exec "$CT_ID" -- bash -c "
        set -e

        # Create audit log monitoring script
        cat > /usr/local/bin/harbor-audit-monitor.sh << 'EOFAUDIT'
#!/bin/bash
# Harbor Audit Log Monitor
# Monitors and alerts on security events

AUDIT_LOG=\"/var/log/harbor/audit.log\"
ALERT_LOG=\"/var/log/harbor/security-alerts.log\"

# Monitor for failed login attempts
FAILED_LOGINS=\$(grep -c \"authentication failed\" \"\$AUDIT_LOG\" 2>/dev/null || echo 0)

if [ \"\$FAILED_LOGINS\" -gt 10 ]; then
    echo \"\$(date): WARNING - \$FAILED_LOGINS failed login attempts detected\" >> \"\$ALERT_LOG\"
fi

# Monitor for unauthorized access attempts
UNAUTHORIZED=\$(grep -c \"unauthorized\" \"\$AUDIT_LOG\" 2>/dev/null || echo 0)

if [ \"\$UNAUTHORIZED\" -gt 5 ]; then
    echo \"\$(date): WARNING - \$UNAUTHORIZED unauthorized access attempts\" >> \"\$ALERT_LOG\"
fi

# Monitor for image deletion events
DELETIONS=\$(grep -c \"artifact deleted\" \"\$AUDIT_LOG\" 2>/dev/null || echo 0)

if [ \"\$DELETIONS\" -gt 0 ]; then
    echo \"\$(date): INFO - \$DELETIONS images deleted\" >> \"\$ALERT_LOG\"
fi
EOFAUDIT

        chmod +x /usr/local/bin/harbor-audit-monitor.sh

        # Schedule hourly audit monitoring
        (crontab -l 2>/dev/null; echo '0 * * * * /usr/local/bin/harbor-audit-monitor.sh') | crontab -
    "

    success "Audit logging configured"
}

# 7. Vulnerability Scanning Policy
configure_vulnerability_policy() {
    echo -e "\n${BLUE}═══ Configuring Vulnerability Scanning Policy ═══${NC}\n"

    info "Vulnerability scanning is configured via Harbor Web UI"
    info "Recommended settings:"
    echo "  - Automatically scan images on push: ENABLED"
    echo "  - Block images with Critical vulnerabilities: TESTING ONLY"
    echo "  - Block images with High vulnerabilities: TESTING ONLY"
    echo "  - Production: Use 'warn' mode instead of 'block'"

    warn "Configure scanning policies after first login to Harbor UI"
}

# 8. Access Control
configure_access_control() {
    echo -e "\n${BLUE}═══ Configuring Access Control ═══${NC}\n"

    info "Access control best practices:"
    echo "  1. Change default admin password immediately"
    echo "  2. Configure LDAP/OIDC authentication"
    echo "  3. Implement least privilege access"
    echo "  4. Use robot accounts for CI/CD (not user credentials)"
    echo "  5. Enable project-level RBAC"
    echo "  6. Regularly audit user permissions"

    warn "Complete access control setup via Harbor Web UI"
}

# 9. Backup Encryption
configure_backup_encryption() {
    echo -e "\n${BLUE}═══ Configuring Encrypted Backups ═══${NC}\n"

    pct exec "$CT_ID" -- bash -c "
        set -e

        # Install encryption tools
        apt-get update
        apt-get install -y gpg

        # Create encrypted backup script
        cat > /usr/local/bin/harbor-backup-encrypted.sh << 'EOFBACKUP'
#!/bin/bash
# Harbor Encrypted Backup Script

BACKUP_DIR=\"${DATA_VOLUME}/backups\"
BACKUP_DATE=\$(date +%Y%m%d)
BACKUP_PATH=\"\$BACKUP_DIR/harbor-backup-\$BACKUP_DATE\"
GPG_RECIPIENT=\"harbor-backup@example.com\"

mkdir -p \"\$BACKUP_PATH\"

# Backup PostgreSQL database
docker exec harbor-db pg_dumpall -U postgres > \"\$BACKUP_PATH/harbor-db.sql\"

# Backup configuration
cp -r /root/harbor/harbor.yml \"\$BACKUP_PATH/\"
cp -r /root/harbor/common/config \"\$BACKUP_PATH/\"

# Backup certificates
cp -r ${DATA_VOLUME}/secrets \"\$BACKUP_PATH/\"

# Create encrypted tarball
tar czf - -C \"\$BACKUP_DIR\" \"harbor-backup-\$BACKUP_DATE\" | \\
    gpg --encrypt --recipient \"\$GPG_RECIPIENT\" > \"\$BACKUP_PATH.tar.gz.gpg\"

# Remove unencrypted backup
rm -rf \"\$BACKUP_PATH\"

# Cleanup old backups (30 days)
find \"\$BACKUP_DIR\" -name \"harbor-backup-*.tar.gz.gpg\" -mtime +30 -delete

echo \"\$(date): Encrypted backup completed\" >> /var/log/harbor-backup.log
EOFBACKUP

        chmod +x /usr/local/bin/harbor-backup-encrypted.sh
    "

    warn "GPG encryption requires key setup - configure GPG recipient before use"
    success "Encrypted backup script created"
}

# 10. Security Monitoring
configure_security_monitoring() {
    echo -e "\n${BLUE}═══ Configuring Security Monitoring ═══${NC}\n"

    pct exec "$CT_ID" -- bash <<'EOF'
        set -e

        # Create security monitoring script
        cat > /usr/local/bin/harbor-security-monitor.sh << 'EOFMONITOR'
#!/bin/bash
# Harbor Security Monitoring Script

REPORT_FILE="/var/log/harbor/security-report-$(date +%Y%m%d).txt"

{
    echo "=== Harbor Security Report ==="
    echo "Generated: $(date)"
    echo ""

    echo "=== Docker Container Status ==="
    docker ps -a
    echo ""

    echo "=== Failed SSH Attempts (Last 24h) ==="
    grep "Failed password" /var/log/auth.log | tail -n 20 || echo "None"
    echo ""

    echo "=== Firewall Rules ==="
    iptables -L -n -v
    echo ""

    echo "=== Disk Usage ==="
    df -h
    echo ""

    echo "=== Harbor Database Connections ==="
    docker exec harbor-db psql -U postgres -c "SELECT count(*) FROM pg_stat_activity;" || echo "Database unavailable"
    echo ""

    echo "=== Recent Security Alerts ==="
    tail -n 50 /var/log/harbor/security-alerts.log 2>/dev/null || echo "No alerts"

} > "$REPORT_FILE"

echo "Security report generated: $REPORT_FILE"
EOFMONITOR

        chmod +x /usr/local/bin/harbor-security-monitor.sh

        # Schedule daily security reports
        (crontab -l 2>/dev/null; echo '0 6 * * * /usr/local/bin/harbor-security-monitor.sh') | crontab -
EOF

    success "Security monitoring configured (daily reports at 6 AM)"
}

# Main Execution
main() {
    info "Starting security hardening for Harbor CT$CT_ID"

    configure_firewall
    harden_ssl_tls
    harden_docker
    harden_filesystem
    harden_system
    configure_audit_logging
    configure_vulnerability_policy
    configure_access_control
    configure_backup_encryption
    configure_security_monitoring

    echo -e "\n${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║     Security Hardening Completed Successfully            ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}\n"

    echo -e "${BLUE}Security Hardening Summary:${NC}"
    echo "  ✓ Firewall configured with restrictive rules"
    echo "  ✓ SSL/TLS hardened (TLS 1.2+ only)"
    echo "  ✓ Docker daemon secured"
    echo "  ✓ File system permissions locked down"
    echo "  ✓ System kernel parameters hardened"
    echo "  ✓ Audit logging enabled"
    echo "  ✓ Encrypted backup script created"
    echo "  ✓ Security monitoring configured"
    echo ""

    echo -e "${YELLOW}Manual Steps Required:${NC}"
    echo "  1. Change Harbor admin password via Web UI"
    echo "  2. Configure LDAP/OIDC authentication"
    echo "  3. Set up GPG encryption for backups"
    echo "  4. Configure vulnerability scanning policies"
    echo "  5. Review and test all security controls"
    echo "  6. Document security procedures"
    echo ""

    success "Harbor CT$CT_ID is now security-hardened"
}

# Run main function
main
