#!/bin/bash
#
# ZFS Alert System - Send notifications for ZFS issues
# Supports email, Slack, webhook, and SMS notifications
#

set -euo pipefail

CONFIG_FILE="/etc/zfs-protection/alert-config.conf"
LOG_FILE="/var/log/zfs-protection/alerts.log"

# Load configuration
source "$CONFIG_FILE" 2>/dev/null || {
    echo "❌ Alert configuration file not found: $CONFIG_FILE"
    exit 1
}

# Parameters
SEVERITY="${1:-INFO}"
POOL="${2:-unknown}"
MESSAGE="${3:-No message provided}"

# Logging function
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [$$] $1" | tee -a "$LOG_FILE"
}

# Generate alert subject and content
generate_alert_content() {
    local severity="$1"
    local pool="$2"
    local message="$3"

    # Choose emoji based on severity
    local emoji
    case "$severity" in
        "CRITICAL") emoji="🚨" ;;
        "WARNING") emoji="⚠️" ;;
        "INFO") emoji="ℹ️" ;;
        *) emoji="📢" ;;
    esac

    # Generate subject
    ALERT_SUBJECT="${emoji} ZFS ${severity}: ${pool} - $(hostname)"

    # Generate detailed message
    ALERT_CONTENT=$(cat <<EOF
${emoji} ZFS Alert - ${severity}

Hostname: $(hostname)
Pool: ${pool}
Time: $(date)
Message: ${message}

Current Pool Status:
$(zpool status "${pool}" 2>/dev/null || echo "Pool status unavailable")

System Information:
- Load Average: $(uptime | awk -F'load average:' '{print $2}')
- Memory Usage: $(free -h | grep '^Mem:' | awk '{print $3 "/" $2}')
- Disk Usage: $(df -h / | tail -1 | awk '{print $5}')

ZFS ARC Status:
$(awk '/^size/ {size=$3} /^c_max/ {max=$3} /^hits/ {hits=$3} /^misses/ {misses=$3} END {
    if (hits > 0 && misses > 0) {
        hit_ratio = hits * 100 / (hits + misses)
        usage = size * 100 / max
        printf "- ARC Size: %.1f%% of max (%.2f GB / %.2f GB)\n", usage, size/1024/1024/1024, max/1024/1024/1024
        printf "- Hit Ratio: %.2f%%\n", hit_ratio
    }
}' /proc/spl/kstat/zfs/arcstats 2>/dev/null || echo "- ARC stats unavailable")

For immediate assistance, check the ZFS protection logs:
- Health Monitor: /var/log/zfs-protection/health-monitor.log
- Scrub Logs: /var/log/zfs-protection/scrub.log
- Backup Logs: /var/log/zfs-protection/backup.log

Generated by ZFS Protection Suite
EOF
)
}

# Send email alert
send_email_alert() {
    if [[ "${EMAIL_ENABLED:-false}" != "true" ]]; then
        log "📧 Email alerts disabled"
        return 0
    fi

    local recipients="${EMAIL_RECIPIENTS:-}"
    if [[ -z "$recipients" ]]; then
        log "❌ No email recipients configured"
        return 1
    fi

    log "📧 Sending email alert to: $recipients"

    # Send via mail command
    if command -v mail >/dev/null 2>&1; then
        echo "$ALERT_CONTENT" | mail -s "$ALERT_SUBJECT" "$recipients"
        if [[ $? -eq 0 ]]; then
            log "✅ Email alert sent successfully"
        else
            log "❌ Failed to send email alert"
            return 1
        fi
    else
        log "❌ Mail command not available"
        return 1
    fi
}

# Send Slack alert
send_slack_alert() {
    if [[ "${SLACK_ENABLED:-false}" != "true" ]]; then
        log "💬 Slack alerts disabled"
        return 0
    fi

    local webhook_url="${SLACK_WEBHOOK_URL:-}"
    if [[ -z "$webhook_url" ]]; then
        log "❌ Slack webhook URL not configured"
        return 1
    fi

    log "💬 Sending Slack alert"

    # Choose color based on severity
    local color
    case "$SEVERITY" in
        "CRITICAL") color="danger" ;;
        "WARNING") color="warning" ;;
        "INFO") color="good" ;;
        *) color="#439FE0" ;;
    esac

    # Create Slack payload
    local payload=$(cat <<EOF
{
    "username": "ZFS Monitor",
    "icon_emoji": ":warning:",
    "attachments": [
        {
            "color": "$color",
            "title": "$ALERT_SUBJECT",
            "text": "$MESSAGE",
            "fields": [
                {
                    "title": "Hostname",
                    "value": "$(hostname)",
                    "short": true
                },
                {
                    "title": "Pool",
                    "value": "$POOL",
                    "short": true
                },
                {
                    "title": "Severity",
                    "value": "$SEVERITY",
                    "short": true
                },
                {
                    "title": "Time",
                    "value": "$(date)",
                    "short": true
                }
            ],
            "footer": "ZFS Protection Suite",
            "ts": $(date +%s)
        }
    ]
}
EOF
)

    # Send to Slack
    if curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            "$webhook_url" \
            --silent --output /dev/null; then
        log "✅ Slack alert sent successfully"
    else
        log "❌ Failed to send Slack alert"
        return 1
    fi
}

# Send webhook alert
send_webhook_alert() {
    if [[ "${WEBHOOK_ENABLED:-false}" != "true" ]]; then
        log "🔗 Webhook alerts disabled"
        return 0
    fi

    local webhook_url="${WEBHOOK_URL:-}"
    if [[ -z "$webhook_url" ]]; then
        log "❌ Webhook URL not configured"
        return 1
    fi

    log "🔗 Sending webhook alert"

    # Create webhook payload
    local payload=$(cat <<EOF
{
    "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
    "hostname": "$(hostname)",
    "severity": "$SEVERITY",
    "pool": "$POOL",
    "message": "$MESSAGE",
    "alert_subject": "$ALERT_SUBJECT",
    "system_info": {
        "load_average": "$(uptime | awk -F'load average:' '{print $2}' | tr -d ' ')",
        "memory_usage": "$(free -h | grep '^Mem:' | awk '{print $3 "/" $2}')",
        "disk_usage": "$(df -h / | tail -1 | awk '{print $5}')"
    }
}
EOF
)

    # Send webhook
    if curl -X POST -H 'Content-Type: application/json' \
            --data "$payload" \
            "$webhook_url" \
            --max-time 10 \
            --silent --output /dev/null; then
        log "✅ Webhook alert sent successfully"
    else
        log "❌ Failed to send webhook alert"
        return 1
    fi
}

# Send SMS alert (via SMS gateway or service)
send_sms_alert() {
    if [[ "${SMS_ENABLED:-false}" != "true" ]]; then
        log "📱 SMS alerts disabled"
        return 0
    fi

    local sms_service="${SMS_SERVICE:-}"
    local sms_recipients="${SMS_RECIPIENTS:-}"

    if [[ -z "$sms_service" ]] || [[ -z "$sms_recipients" ]]; then
        log "❌ SMS service or recipients not configured"
        return 1
    fi

    log "📱 Sending SMS alert"

    # Truncate message for SMS
    local sms_message="ZFS ${SEVERITY}: ${POOL} on $(hostname) - ${MESSAGE}"
    if [[ ${#sms_message} -gt 160 ]]; then
        sms_message="${sms_message:0:157}..."
    fi

    case "$sms_service" in
        "twilio")
            if [[ -n "${TWILIO_ACCOUNT_SID:-}" ]] && [[ -n "${TWILIO_AUTH_TOKEN:-}" ]] && [[ -n "${TWILIO_FROM_NUMBER:-}" ]]; then
                for recipient in $(echo "$sms_recipients" | tr ',' ' '); do
                    curl -X POST "https://api.twilio.com/2010-04-01/Accounts/${TWILIO_ACCOUNT_SID}/Messages.json" \
                        --data-urlencode "From=${TWILIO_FROM_NUMBER}" \
                        --data-urlencode "To=${recipient}" \
                        --data-urlencode "Body=${sms_message}" \
                        -u "${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}" \
                        --silent --output /dev/null
                done
                log "✅ SMS alerts sent via Twilio"
            else
                log "❌ Twilio configuration incomplete"
                return 1
            fi
            ;;
        "custom")
            # Use custom SMS script if provided
            if [[ -n "${SMS_SCRIPT:-}" ]] && [[ -x "$SMS_SCRIPT" ]]; then
                "$SMS_SCRIPT" "$sms_recipients" "$sms_message"
                log "✅ SMS alerts sent via custom script"
            else
                log "❌ Custom SMS script not found or not executable"
                return 1
            fi
            ;;
        *)
            log "❌ Unknown SMS service: $sms_service"
            return 1
            ;;
    esac
}

# Write alert to log for audit trail
write_alert_log() {
    local alert_log="/var/log/zfs-protection/alert-audit.log"

    {
        echo "{"
        echo "  \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\","
        echo "  \"hostname\": \"$(hostname)\","
        echo "  \"severity\": \"$SEVERITY\","
        echo "  \"pool\": \"$POOL\","
        echo "  \"message\": \"$MESSAGE\","
        echo "  \"methods_attempted\": ["

        local methods_attempted=false
        if [[ "${EMAIL_ENABLED:-false}" == "true" ]]; then
            echo "    \"email\""
            methods_attempted=true
        fi

        if [[ "${SLACK_ENABLED:-false}" == "true" ]]; then
            [[ "$methods_attempted" == "true" ]] && echo ","
            echo "    \"slack\""
            methods_attempted=true
        fi

        if [[ "${WEBHOOK_ENABLED:-false}" == "true" ]]; then
            [[ "$methods_attempted" == "true" ]] && echo ","
            echo "    \"webhook\""
            methods_attempted=true
        fi

        if [[ "${SMS_ENABLED:-false}" == "true" ]]; then
            [[ "$methods_attempted" == "true" ]] && echo ","
            echo "    \"sms\""
        fi

        echo "  ]"
        echo "},"
    } >> "$alert_log"
}

# Rate limiting to prevent alert spam
check_rate_limit() {
    local rate_limit_file="/tmp/zfs-alert-rate-limit-${POOL}-${SEVERITY}"
    local rate_limit_seconds="${ALERT_RATE_LIMIT:-300}"  # 5 minutes default

    if [[ -f "$rate_limit_file" ]]; then
        local last_alert_time
        last_alert_time=$(cat "$rate_limit_file")
        local current_time
        current_time=$(date +%s)

        if [[ $((current_time - last_alert_time)) -lt $rate_limit_seconds ]]; then
            log "🔒 Alert rate limited for $POOL ($SEVERITY) - last alert was $((current_time - last_alert_time))s ago"
            return 1
        fi
    fi

    echo "$(date +%s)" > "$rate_limit_file"
    return 0
}

# Main alert function
main() {
    # Validate severity level
    case "$SEVERITY" in
        "CRITICAL"|"WARNING"|"INFO")
            ;;
        *)
            log "❌ Invalid severity level: $SEVERITY"
            exit 1
            ;;
    esac

    log "🚨 Processing alert: $SEVERITY - $POOL - $MESSAGE"

    # Check rate limiting
    if ! check_rate_limit; then
        exit 0
    fi

    # Generate alert content
    generate_alert_content "$SEVERITY" "$POOL" "$MESSAGE"

    # Write to audit log
    write_alert_log

    # Send alerts via configured methods
    local success_count=0
    local total_methods=0

    # Email
    if [[ "${EMAIL_ENABLED:-false}" == "true" ]]; then
        total_methods=$((total_methods + 1))
        if send_email_alert; then
            success_count=$((success_count + 1))
        fi
    fi

    # Slack
    if [[ "${SLACK_ENABLED:-false}" == "true" ]]; then
        total_methods=$((total_methods + 1))
        if send_slack_alert; then
            success_count=$((success_count + 1))
        fi
    fi

    # Webhook
    if [[ "${WEBHOOK_ENABLED:-false}" == "true" ]]; then
        total_methods=$((total_methods + 1))
        if send_webhook_alert; then
            success_count=$((success_count + 1))
        fi
    fi

    # SMS
    if [[ "${SMS_ENABLED:-false}" == "true" ]]; then
        total_methods=$((total_methods + 1))
        if send_sms_alert; then
            success_count=$((success_count + 1))
        fi
    fi

    # Summary
    if [[ $total_methods -eq 0 ]]; then
        log "⚠️ No alert methods configured"
        exit 1
    elif [[ $success_count -eq $total_methods ]]; then
        log "✅ All alerts sent successfully ($success_count/$total_methods)"
        exit 0
    elif [[ $success_count -gt 0 ]]; then
        log "⚠️ Some alerts failed ($success_count/$total_methods)"
        exit 1
    else
        log "❌ All alerts failed (0/$total_methods)"
        exit 1
    fi
}

# Test mode
if [[ "${1:-}" == "--test" ]]; then
    echo "🧪 Testing alert system..."
    SEVERITY="INFO"
    POOL="test-pool"
    MESSAGE="This is a test alert from the ZFS protection system"

    # Generate test content
    generate_alert_content "$SEVERITY" "$POOL" "$MESSAGE"

    echo "Subject: $ALERT_SUBJECT"
    echo ""
    echo "Content:"
    echo "$ALERT_CONTENT"
    echo ""
    echo "Configuration:"
    echo "- Email: ${EMAIL_ENABLED:-false} (${EMAIL_RECIPIENTS:-not set})"
    echo "- Slack: ${SLACK_ENABLED:-false}"
    echo "- Webhook: ${WEBHOOK_ENABLED:-false}"
    echo "- SMS: ${SMS_ENABLED:-false}"

    exit 0
fi

# Help
if [[ "${1:-}" == "--help" ]] || [[ "${1:-}" == "-h" ]]; then
    echo "Usage: $0 <severity> <pool> <message>"
    echo ""
    echo "Severity levels: CRITICAL, WARNING, INFO"
    echo ""
    echo "Examples:"
    echo "  $0 CRITICAL tank 'Pool is degraded'"
    echo "  $0 WARNING rpool 'High capacity usage'"
    echo "  $0 INFO backup 'Backup completed successfully'"
    echo ""
    echo "Test mode:"
    echo "  $0 --test"
    exit 0
fi

# Run main function
main