#!/bin/bash
#
# ZFS Tuning Script - Optimize ZFS parameters for data protection and performance
# Applies best practices for ZFS configuration on Proxmox systems
#

set -euo pipefail

LOG_FILE="/var/log/zfs-protection/tuning.log"
BACKUP_DIR="/etc/zfs-protection/tuning-backups"

# Logging function
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [$$] $1" | tee -a "$LOG_FILE"
}

# Create backup directory
mkdir -p "$BACKUP_DIR"

# Backup current settings
backup_current_settings() {
    local backup_file="$BACKUP_DIR/zfs-settings-$(date +%Y%m%d_%H%M%S).txt"

    log "📋 Backing up current ZFS settings to: $backup_file"

    {
        echo "# ZFS Settings Backup - $(date)"
        echo "# Generated before applying tuning optimizations"
        echo ""

        echo "# ZFS Module Parameters"
        if [[ -d /sys/module/zfs/parameters ]]; then
            for param in /sys/module/zfs/parameters/*; do
                if [[ -f "$param" ]]; then
                    param_name=$(basename "$param")
                    param_value=$(cat "$param" 2>/dev/null || echo "unreadable")
                    echo "zfs.${param_name}=${param_value}"
                fi
            done
        fi

        echo ""
        echo "# Pool Properties"
        for pool in $(zpool list -H -o name 2>/dev/null || echo ""); do
            if [[ -n "$pool" ]]; then
                echo "# Pool: $pool"
                zpool get all "$pool" | grep -v "^NAME"
                echo ""
            fi
        done

        echo "# Dataset Properties"
        for dataset in $(zfs list -H -o name -t filesystem 2>/dev/null || echo ""); do
            if [[ -n "$dataset" ]]; then
                echo "# Dataset: $dataset"
                zfs get all "$dataset" | grep -v "^NAME"
                echo ""
            fi
        done
    } > "$backup_file"

    log "✅ Current settings backed up successfully"
}

# Get system memory size
get_system_memory() {
    local mem_kb
    mem_kb=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    echo $((mem_kb * 1024))  # Convert to bytes
}

# Get recommended ARC size
get_recommended_arc_size() {
    local total_mem
    total_mem=$(get_system_memory)

    # For Proxmox systems, leave memory for VMs
    # Use 25% of total memory for ARC, with minimum 1GB and maximum 8GB
    local arc_size=$((total_mem / 4))

    # Minimum 1GB
    local min_arc=$((1 * 1024 * 1024 * 1024))
    if [[ $arc_size -lt $min_arc ]]; then
        arc_size=$min_arc
    fi

    # Maximum 8GB for typical Proxmox setups
    local max_arc=$((8 * 1024 * 1024 * 1024))
    if [[ $arc_size -gt $max_arc ]]; then
        arc_size=$max_arc
    fi

    echo $arc_size
}

# Apply ZFS module parameters
apply_zfs_module_params() {
    log "⚙️ Applying ZFS module parameters..."

    local total_mem arc_max
    total_mem=$(get_system_memory)
    arc_max=$(get_recommended_arc_size)

    # Create modprobe configuration
    local modprobe_file="/etc/modprobe.d/zfs-tuning.conf"

    cat > "$modprobe_file" <<EOF
# ZFS Tuning Parameters for Data Protection and Performance
# Generated by ZFS Protection Suite - $(date)

# ARC (Adaptive Replacement Cache) Settings
options zfs zfs_arc_max=$arc_max
options zfs zfs_arc_min=$((arc_max / 2))

# Memory management
options zfs zfs_arc_meta_limit=$((arc_max / 4))
options zfs zfs_arc_meta_limit_percent=25
options zfs zfs_arc_dnode_limit_percent=10

# Transaction Group (TXG) Settings for better write performance
options zfs zfs_txg_timeout=5
options zfs zfs_dirty_data_max=$((total_mem / 10))
options zfs zfs_dirty_data_max_percent=10
options zfs zfs_dirty_data_sync_percent=20

# L2ARC Settings (if SSD cache is available)
options zfs l2arc_write_max=134217728
options zfs l2arc_headroom=2
options zfs l2arc_feed_secs=1

# ZIL (ZFS Intent Log) Settings
options zfs zfs_immediate_write_sz=32768
options zfs zfs_sync_pass_deferred_free=2

# Scrub and resilver tuning
options zfs zfs_scrub_delay=4
options zfs zfs_resilver_delay=2
options zfs zfs_scan_idle=50

# VDEV settings for reliability
options zfs zfs_vdev_scheduler=deadline
options zfs zfs_vdev_async_write_active_max_dirty_percent=60

# Prefetch tuning
options zfs zfs_prefetch_disable=0
options zfs zfetch_max_streams=8
options zfs zfetch_min_sec_reap=2

# Checksum and compression
options zfs zfs_fletcher_4_impl=fastest
options zfs zfs_admin_snapshot=1

# Deadlock prevention
options zfs zfs_deadman_enabled=1
options zfs zfs_deadman_synctime_ms=600000
options zfs zfs_deadman_ziotime_ms=300000

# Multi-modifier protection
options zfs zfs_multihost_interval=1000
options zfs zfs_multihost_fail_intervals=5

EOF

    log "✅ ZFS module parameters configured in: $modprobe_file"
    log "⚠️ Reboot required for module parameters to take effect"
}

# Apply runtime tunable parameters
apply_runtime_tunables() {
    log "⚙️ Applying runtime tunable parameters..."

    # Parameters that can be changed at runtime
    local runtime_params=(
        # ARC parameters
        "zfs_arc_meta_limit_percent 25"
        "zfs_arc_dnode_limit_percent 10"

        # Transaction group settings
        "zfs_txg_timeout 5"
        "zfs_dirty_data_sync_percent 20"

        # Scrub and resilver settings
        "zfs_scrub_delay 4"
        "zfs_resilver_delay 2"
        "zfs_scan_idle 50"

        # Prefetch settings
        "zfetch_max_streams 8"
        "zfetch_min_sec_reap 2"

        # Deadlock prevention
        "zfs_deadman_synctime_ms 600000"
        "zfs_deadman_ziotime_ms 300000"
    )

    for param_line in "${runtime_params[@]}"; do
        local param_name param_value
        read -r param_name param_value <<< "$param_line"

        local param_path="/sys/module/zfs/parameters/$param_name"

        if [[ -f "$param_path" ]]; then
            local current_value
            current_value=$(cat "$param_path" 2>/dev/null || echo "unknown")

            if [[ "$current_value" != "$param_value" ]]; then
                if echo "$param_value" > "$param_path" 2>/dev/null; then
                    log "✅ Set $param_name: $current_value → $param_value"
                else
                    log "⚠️ Failed to set $param_name to $param_value (may require reboot)"
                fi
            else
                log "✅ $param_name already set to $param_value"
            fi
        else
            log "⚠️ Parameter $param_name not found (may require module reload)"
        fi
    done
}

# Apply pool-level optimizations
apply_pool_optimizations() {
    log "🏊 Applying pool-level optimizations..."

    for pool in $(zpool list -H -o name 2>/dev/null || echo ""); do
        if [[ -z "$pool" ]]; then
            continue
        fi

        log "📊 Optimizing pool: $pool"

        # Set optimal pool properties
        local pool_properties=(
            "autotrim on"
            "failmode wait"
            "multihost off"
        )

        for prop_line in "${pool_properties[@]}"; do
            local prop_name prop_value
            read -r prop_name prop_value <<< "$prop_line"

            local current_value
            current_value=$(zpool get -H -o value "$prop_name" "$pool" 2>/dev/null || echo "unknown")

            if [[ "$current_value" != "$prop_value" ]]; then
                if zpool set "$prop_name=$prop_value" "$pool" 2>/dev/null; then
                    log "✅ Pool $pool: Set $prop_name: $current_value → $prop_value"
                else
                    log "⚠️ Pool $pool: Failed to set $prop_name to $prop_value"
                fi
            else
                log "✅ Pool $pool: $prop_name already set to $prop_value"
            fi
        done
    done
}

# Apply dataset-level optimizations
apply_dataset_optimizations() {
    log "📁 Applying dataset-level optimizations..."

    for dataset in $(zfs list -H -o name -t filesystem 2>/dev/null || echo ""); do
        if [[ -z "$dataset" ]]; then
            continue
        fi

        # Skip backup datasets and snapshots
        if [[ "$dataset" =~ ^backup/ ]] || [[ "$dataset" =~ @ ]]; then
            continue
        fi

        log "📊 Optimizing dataset: $dataset"

        # Determine dataset type and apply appropriate settings
        local mountpoint
        mountpoint=$(zfs get -H -o value mountpoint "$dataset" 2>/dev/null || echo "none")

        # Default optimizations for all datasets
        local dataset_properties=(
            "atime off"
            "compression lz4"
            "checksum sha256"
            "redundant_metadata most"
            "xattr sa"
            "dnodesize auto"
        )

        # VM/Container specific optimizations
        if [[ "$mountpoint" =~ /var/lib/vz ]] || [[ "$dataset" =~ vm-|ct- ]]; then
            dataset_properties+=(
                "recordsize 64K"
                "sync standard"
                "primarycache metadata"
                "logbias throughput"
            )
            log "📦 Applying VM/Container optimizations to: $dataset"
        # General purpose optimizations
        else
            dataset_properties+=(
                "recordsize 128K"
                "sync standard"
                "primarycache all"
                "secondarycache all"
            )
        fi

        for prop_line in "${dataset_properties[@]}"; do
            local prop_name prop_value
            read -r prop_name prop_value <<< "$prop_line"

            local current_value
            current_value=$(zfs get -H -o value "$prop_name" "$dataset" 2>/dev/null || echo "unknown")

            if [[ "$current_value" != "$prop_value" ]] && [[ "$current_value" != "inherited" ]]; then
                if zfs set "$prop_name=$prop_value" "$dataset" 2>/dev/null; then
                    log "✅ Dataset $dataset: Set $prop_name: $current_value → $prop_value"
                else
                    log "⚠️ Dataset $dataset: Failed to set $prop_name to $prop_value"
                fi
            else
                log "✅ Dataset $dataset: $prop_name already optimal ($current_value)"
            fi
        done
    done
}

# Apply kernel settings
apply_kernel_settings() {
    log "🔧 Applying kernel settings for ZFS..."

    # Create sysctl configuration
    local sysctl_file="/etc/sysctl.d/90-zfs-tuning.conf"

    cat > "$sysctl_file" <<EOF
# ZFS Kernel Tuning Parameters
# Generated by ZFS Protection Suite - $(date)

# Virtual memory settings for ZFS
vm.swappiness=1
vm.vfs_cache_pressure=50
vm.dirty_background_ratio=5
vm.dirty_ratio=10
vm.dirty_expire_centisecs=3000
vm.dirty_writeback_centisecs=500

# Network settings for ZFS replication
net.core.rmem_default=262144
net.core.rmem_max=16777216
net.core.wmem_default=262144
net.core.wmem_max=16777216

# Kernel settings for better I/O performance
kernel.pid_max=65536

EOF

    # Apply settings immediately
    if sysctl -p "$sysctl_file" >/dev/null 2>&1; then
        log "✅ Kernel settings applied: $sysctl_file"
    else
        log "⚠️ Some kernel settings may require reboot to take effect"
    fi
}

# Generate tuning report
generate_tuning_report() {
    local report_file="/var/log/zfs-protection/tuning-report-$(date +%Y%m%d_%H%M%S).txt"

    log "📄 Generating tuning report: $report_file"

    {
        echo "🔧 ZFS Tuning Report - $(date)"
        echo "=============================================="
        echo ""

        echo "🖥️ System Information:"
        echo "Hostname: $(hostname)"
        echo "Total Memory: $(( $(get_system_memory) / 1024 / 1024 / 1024 ))GB"
        echo "Recommended ARC Max: $(( $(get_recommended_arc_size) / 1024 / 1024 / 1024 ))GB"
        echo ""

        echo "🏊 Pool Status:"
        zpool status
        echo ""

        echo "📊 Pool Properties:"
        for pool in $(zpool list -H -o name 2>/dev/null || echo ""); do
            if [[ -n "$pool" ]]; then
                echo "Pool: $pool"
                zpool get all "$pool" | grep -E "(autotrim|failmode|multihost)"
                echo ""
            fi
        done

        echo "📁 Dataset Properties (sample):"
        for dataset in $(zfs list -H -o name -t filesystem | head -5); do
            echo "Dataset: $dataset"
            zfs get compression,checksum,atime,recordsize "$dataset"
            echo ""
        done

        echo "⚙️ Current ZFS Module Parameters (key settings):"
        for param in zfs_arc_max zfs_arc_min zfs_txg_timeout zfs_dirty_data_max_percent; do
            local param_path="/sys/module/zfs/parameters/$param"
            if [[ -f "$param_path" ]]; then
                local value
                value=$(cat "$param_path" 2>/dev/null || echo "unknown")
                echo "$param: $value"
            fi
        done
        echo ""

        echo "🔧 Applied Configurations:"
        echo "- Module parameters: /etc/modprobe.d/zfs-tuning.conf"
        echo "- Kernel settings: /etc/sysctl.d/90-zfs-tuning.conf"
        echo "- Backup directory: $BACKUP_DIR"
        echo ""

        echo "📋 Next Steps:"
        echo "1. Reboot system for all module parameters to take effect"
        echo "2. Monitor ZFS performance with: zpool iostat -v"
        echo "3. Check ARC statistics with: cat /proc/spl/kstat/zfs/arcstats"
        echo "4. Review pool health regularly with health monitor"

    } > "$report_file"

    log "✅ Tuning report generated: $report_file"
}

# Validate ZFS configuration
validate_configuration() {
    log "🔍 Validating ZFS configuration..."

    local validation_errors=0

    # Check if ZFS is loaded
    if ! lsmod | grep -q "^zfs "; then
        log "❌ ZFS module not loaded"
        validation_errors=$((validation_errors + 1))
    else
        log "✅ ZFS module is loaded"
    fi

    # Check pool health
    for pool in $(zpool list -H -o name 2>/dev/null || echo ""); do
        if [[ -n "$pool" ]]; then
            local health
            health=$(zpool get -H -o value health "$pool")
            if [[ "$health" == "ONLINE" ]]; then
                log "✅ Pool $pool is healthy"
            else
                log "❌ Pool $pool health: $health"
                validation_errors=$((validation_errors + 1))
            fi
        fi
    done

    # Check ARC size
    if [[ -f /proc/spl/kstat/zfs/arcstats ]]; then
        local arc_size arc_max
        arc_size=$(awk '/^size/ {print $3}' /proc/spl/kstat/zfs/arcstats)
        arc_max=$(awk '/^c_max/ {print $3}' /proc/spl/kstat/zfs/arcstats)

        if [[ "$arc_size" -gt 0 ]] && [[ "$arc_max" -gt 0 ]]; then
            log "✅ ARC is functioning (Size: $(( arc_size / 1024 / 1024 ))MB, Max: $(( arc_max / 1024 / 1024 ))MB)"
        else
            log "❌ ARC statistics appear invalid"
            validation_errors=$((validation_errors + 1))
        fi
    else
        log "❌ Cannot read ARC statistics"
        validation_errors=$((validation_errors + 1))
    fi

    if [[ $validation_errors -eq 0 ]]; then
        log "✅ ZFS configuration validation passed"
        return 0
    else
        log "❌ ZFS configuration validation failed ($validation_errors errors)"
        return 1
    fi
}

# Main function
main() {
    local operation="${1:-all}"

    log "🚀 Starting ZFS tuning process (operation: $operation)"

    case "$operation" in
        "backup")
            backup_current_settings
            ;;
        "module")
            backup_current_settings
            apply_zfs_module_params
            ;;
        "runtime")
            apply_runtime_tunables
            ;;
        "pools")
            apply_pool_optimizations
            ;;
        "datasets")
            apply_dataset_optimizations
            ;;
        "kernel")
            apply_kernel_settings
            ;;
        "validate")
            validate_configuration
            ;;
        "report")
            generate_tuning_report
            ;;
        "all")
            backup_current_settings
            apply_zfs_module_params
            apply_runtime_tunables
            apply_pool_optimizations
            apply_dataset_optimizations
            apply_kernel_settings
            generate_tuning_report
            validate_configuration

            log ""
            log "✅ ZFS tuning completed successfully!"
            log "⚠️ Reboot recommended for all optimizations to take effect"
            log "📄 Review the tuning report for details"
            ;;
        *)
            echo "Usage: $0 [backup|module|runtime|pools|datasets|kernel|validate|report|all]"
            echo ""
            echo "Operations:"
            echo "  backup    Backup current ZFS settings"
            echo "  module    Apply ZFS module parameters (requires reboot)"
            echo "  runtime   Apply runtime tunable parameters"
            echo "  pools     Apply pool-level optimizations"
            echo "  datasets  Apply dataset-level optimizations"
            echo "  kernel    Apply kernel settings"
            echo "  validate  Validate ZFS configuration"
            echo "  report    Generate tuning report"
            echo "  all       Apply all optimizations (default)"
            echo ""
            echo "Examples:"
            echo "  $0 all        # Apply all optimizations"
            echo "  $0 backup     # Backup settings only"
            echo "  $0 validate   # Validate configuration"
            exit 1
            ;;
    esac
}

# Run main function
main "$@"