#!/bin/bash
# iSCSI Target Configuration Script for AGLSRV1
# Generated by System Architect Agent
# Date: 2025-10-14

set -euo pipefail

# ============================================================================
# Configuration Variables
# ============================================================================

STORAGE_ROOT="/mnt/storage/iscsi"
TARGET_IQN="iqn.2025-01.local.aglsrv1:storage"
TAILSCALE_SUBNET="100.0.0.0/8"

# Remote hosts configuration
declare -A HOSTS=(
  ["aglsrv6"]="100.98.108.66"
  ["aglsrv6b"]="100.98.119.51"
  ["fgsrv5"]="100.71.107.26"
  ["fgsrv6"]="100.83.51.9"
)

# LUN sizes (in GB)
DEFAULT_LUN_SIZE="500G"

# ============================================================================
# Functions
# ============================================================================

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a /var/log/iscsi-setup.log
}

error() {
  log "ERROR: $*"
  exit 1
}

check_prerequisites() {
  log "Checking prerequisites..."

  # Check if running as root
  [[ $EUID -ne 0 ]] && error "This script must be run as root"

  # Check if targetcli is installed
  command -v targetcli &>/dev/null || error "targetcli not installed. Run: apt install targetcli-fb"

  # Check if storage directory exists
  [[ -d "$STORAGE_ROOT" ]] || mkdir -p "$STORAGE_ROOT"

  log "Prerequisites check passed"
}

create_lun_file() {
  local hostname=$1
  local size=${2:-$DEFAULT_LUN_SIZE}
  local lun_file="$STORAGE_ROOT/lun-${hostname}-001.img"

  if [[ -f "$lun_file" ]]; then
    log "LUN file for $hostname already exists: $lun_file"
    return 0
  fi

  log "Creating $size LUN file for $hostname..."
  fallocate -l "$size" "$lun_file" || error "Failed to create LUN file: $lun_file"
  chmod 600 "$lun_file"
  log "Created LUN: $lun_file"
}

generate_chap_password() {
  openssl rand -base64 16 | tr -d '=/+' | cut -c1-16
}

configure_iscsi_target() {
  log "Configuring iSCSI target..."

  # Create backstores for each host
  for hostname in "${!HOSTS[@]}"; do
    local lun_file="$STORAGE_ROOT/lun-${hostname}-001.img"
    create_lun_file "$hostname" "$DEFAULT_LUN_SIZE"

    log "Creating backstore for $hostname..."
    targetcli /backstores/fileio create "lun-${hostname}-001" "$lun_file" || log "Backstore already exists"
  done

  # Create iSCSI target
  log "Creating iSCSI target: $TARGET_IQN"
  targetcli /iscsi create "$TARGET_IQN" || log "Target already exists"

  # Add LUNs to target
  log "Adding LUNs to target..."
  for hostname in "${!HOSTS[@]}"; do
    targetcli "/iscsi/${TARGET_IQN}/tpg1/luns" create "/backstores/fileio/lun-${hostname}-001" || log "LUN already added"
  done

  # Configure ACLs and CHAP authentication
  log "Configuring ACLs and authentication..."
  for hostname in "${!HOSTS[@]}"; do
    local initiator_iqn="iqn.2025-01.local.${hostname}:initiator"
    local chap_user="$hostname"
    local chap_pass=$(generate_chap_password)

    # Create ACL
    targetcli "/iscsi/${TARGET_IQN}/tpg1/acls" create "$initiator_iqn" || log "ACL already exists"

    # Set CHAP authentication
    targetcli "/iscsi/${TARGET_IQN}/tpg1/acls/${initiator_iqn}" set auth userid="$chap_user" || log "CHAP user already set"
    targetcli "/iscsi/${TARGET_IQN}/tpg1/acls/${initiator_iqn}" set auth password="$chap_pass" || log "CHAP password already set"

    # Save credentials for client configuration
    echo "$hostname:$chap_user:$chap_pass" >> /root/iscsi-chap-credentials.txt
    log "Configured ACL for $hostname with CHAP authentication"
  done

  # Configure portals (bind to Tailscale IPs)
  log "Configuring network portals..."
  local tailscale_ip=$(ip -4 addr show tailscale0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')

  if [[ -n "$tailscale_ip" ]]; then
    # Remove default 0.0.0.0 portal
    targetcli "/iscsi/${TARGET_IQN}/tpg1/portals" delete 0.0.0.0 3260 || log "Default portal already removed"

    # Add Tailscale IP portal
    targetcli "/iscsi/${TARGET_IQN}/tpg1/portals" create "$tailscale_ip" 3260 || log "Tailscale portal already exists"
    log "Configured portal on Tailscale IP: $tailscale_ip"
  else
    log "WARNING: Tailscale IP not found, using default portal"
  fi

  # Save configuration
  log "Saving iSCSI configuration..."
  targetcli saveconfig

  log "iSCSI target configuration completed successfully"
}

configure_firewall() {
  log "Configuring firewall rules..."

  if command -v ufw &>/dev/null; then
    ufw allow from "$TAILSCALE_SUBNET" to any port 3260 proto tcp comment "iSCSI from Tailscale network"
    log "UFW rule added for iSCSI"
  elif command -v firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --add-rich-rule="rule family='ipv4' source address='$TAILSCALE_SUBNET' port protocol='tcp' port='3260' accept"
    firewall-cmd --reload
    log "firewalld rule added for iSCSI"
  else
    log "WARNING: No supported firewall found (ufw/firewalld)"
  fi
}

enable_services() {
  log "Enabling and starting iSCSI target service..."

  systemctl enable target || error "Failed to enable target service"
  systemctl restart target || error "Failed to start target service"
  systemctl status target --no-pager

  log "iSCSI target service is running"
}

display_client_config() {
  log "==================================================================="
  log "iSCSI Target Setup Complete!"
  log "==================================================================="
  log ""
  log "Target IQN: $TARGET_IQN"
  log "Portal: $(ip -4 addr show tailscale0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'):3260"
  log ""
  log "Client Configuration Instructions:"
  log "-----------------------------------"
  log ""

  for hostname in "${!HOSTS[@]}"; do
    local ip="${HOSTS[$hostname]}"
    log "For $hostname ($ip):"
    log "  1. Set initiator name:"
    log "     echo 'InitiatorName=iqn.2025-01.local.${hostname}:initiator' > /etc/iscsi/initiatorname.iscsi"
    log ""
    log "  2. Configure CHAP authentication in /etc/iscsi/iscsid.conf:"
    log "     node.session.auth.authmethod = CHAP"
    log "     node.session.auth.username = $(grep "^${hostname}:" /root/iscsi-chap-credentials.txt | cut -d: -f2)"
    log "     node.session.auth.password = $(grep "^${hostname}:" /root/iscsi-chap-credentials.txt | cut -d: -f3)"
    log ""
    log "  3. Discover and login:"
    log "     iscsiadm -m discovery -t st -p $(ip -4 addr show tailscale0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'):3260"
    log "     iscsiadm -m node --targetname $TARGET_IQN --portal $(ip -4 addr show tailscale0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'):3260 --login"
    log ""
  done

  log "CHAP credentials saved to: /root/iscsi-chap-credentials.txt"
  log "==================================================================="
}

# ============================================================================
# Main Execution
# ============================================================================

main() {
  log "Starting iSCSI target setup for AGLSRV1..."

  check_prerequisites
  configure_iscsi_target
  configure_firewall
  enable_services
  display_client_config

  log "iSCSI target setup completed successfully!"
}

main "$@"
