#!/bin/bash
# Proxmox Backup Server Datastore Configuration Script
# Generated by System Architect Agent
# Date: 2025-10-14

set -euo pipefail

# ============================================================================
# Configuration Variables
# ============================================================================

STORAGE_ROOT="/mnt/storage/remote"
PBS_API_URL="https://localhost:8007"

# Remote hosts configuration
declare -A HOSTS=(
  ["aglsrv6"]="100.98.108.66"
  ["aglsrv6b"]="100.98.119.51"
  ["fgsrv5"]="100.71.107.26"
  ["fgsrv6"]="100.83.51.9"
)

# ============================================================================
# Functions
# ============================================================================

log() {
  echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*" | tee -a /var/log/pbs-setup.log
}

error() {
  log "ERROR: $*"
  exit 1
}

check_prerequisites() {
  log "Checking prerequisites..."

  # Check if running as root
  [[ $EUID -ne 0 ]] && error "This script must be run as root"

  # Check if PBS is installed
  command -v proxmox-backup-manager &>/dev/null || error "Proxmox Backup Server not installed"

  # Check if storage root exists
  [[ -d "$STORAGE_ROOT" ]] || error "Storage root does not exist: $STORAGE_ROOT"

  log "Prerequisites check passed"
}

create_datastore_directories() {
  log "Creating datastore directories..."

  for hostname in "${!HOSTS[@]}"; do
    local datastore_path="$STORAGE_ROOT/$hostname/backups"

    if [[ ! -d "$datastore_path" ]]; then
      mkdir -p "$datastore_path"
      log "Created datastore directory: $datastore_path"
    else
      log "Datastore directory already exists: $datastore_path"
    fi

    # Set proper permissions
    chown -R backup:backup "$datastore_path" 2>/dev/null || log "backup user not yet created"
    chmod 700 "$datastore_path"
  done
}

create_pbs_datastores() {
  log "Creating PBS datastores..."

  local gc_offset=0
  for hostname in "${!HOSTS[@]}"; do
    local datastore_name="remote-$hostname"
    local datastore_path="$STORAGE_ROOT/$hostname/backups"

    # Calculate GC schedule with 15-minute offset per host
    local gc_hour=2
    local gc_min=$((gc_offset * 15))
    if [[ $gc_min -ge 60 ]]; then
      gc_hour=$((gc_hour + gc_min / 60))
      gc_min=$((gc_min % 60))
    fi
    local gc_schedule=$(printf "daily %02d:%02d" $gc_hour $gc_min)

    # Calculate prune schedule (1 hour after GC)
    local prune_hour=$((gc_hour + 1))
    local prune_schedule=$(printf "daily %02d:%02d" $prune_hour $gc_min)

    log "Creating datastore: $datastore_name"
    log "  Path: $datastore_path"
    log "  GC Schedule: $gc_schedule"
    log "  Prune Schedule: $prune_schedule"

    # Create datastore using proxmox-backup-manager
    if proxmox-backup-manager datastore list | grep -q "^│ $datastore_name"; then
      log "Datastore $datastore_name already exists, skipping creation"
    else
      proxmox-backup-manager datastore create "$datastore_name" \
        --path "$datastore_path" \
        --gc-schedule "$gc_schedule" \
        --prune-schedule "$prune_schedule" \
        --comment "Backup storage for $hostname (${HOSTS[$hostname]})" || error "Failed to create datastore: $datastore_name"
      log "Created datastore: $datastore_name"
    fi

    ((gc_offset++))
  done
}

create_backup_user() {
  log "Creating PBS backup user..."

  local username="backup@pbs"

  # Check if user exists
  if proxmox-backup-manager user list | grep -q "$username"; then
    log "User $username already exists"
  else
    # Create user
    proxmox-backup-manager user create "$username" \
      --comment "Remote host backup user" || error "Failed to create user: $username"
    log "Created user: $username"
  fi

  # Generate API token
  local token_name="remote-backup"
  log "Creating API token for remote access..."

  if proxmox-backup-manager user list-tokens | grep -q "$username!$token_name"; then
    log "API token $username!$token_name already exists"
  else
    local token_secret=$(proxmox-backup-manager user generate-token "$username" "$token_name" --output-format=json | jq -r '.value')
    log "Created API token: $username!$token_name"
    log "Token secret: $token_secret"

    # Save token to file
    echo "$username!$token_name:$token_secret" > /root/pbs-api-token.txt
    chmod 600 /root/pbs-api-token.txt
    log "Token saved to: /root/pbs-api-token.txt"
  fi
}

configure_datastore_permissions() {
  log "Configuring datastore permissions..."

  local username="backup@pbs"

  for hostname in "${!HOSTS[@]}"; do
    local datastore_name="remote-$hostname"

    # Grant permissions to backup user
    pveum acl modify "/datastore/$datastore_name" \
      --roles DatastoreBackup,DatastoreReader,DatastoreVerify \
      --users "$username" 2>/dev/null || log "ACL already configured for $datastore_name"

    log "Configured permissions for $datastore_name"
  done
}

configure_retention_policy() {
  log "Configuring retention policies..."

  for hostname in "${!HOSTS[@]}"; do
    local datastore_name="remote-$hostname"

    # Default retention policy: 7 daily, 4 weekly, 6 monthly
    proxmox-backup-manager datastore update "$datastore_name" \
      --keep-daily 7 \
      --keep-weekly 4 \
      --keep-monthly 6 || log "Retention policy already set for $datastore_name"

    log "Configured retention policy for $datastore_name"
  done
}

enable_verification_jobs() {
  log "Enabling verification jobs..."

  local verify_offset=0
  for hostname in "${!HOSTS[@]}"; do
    local datastore_name="remote-$hostname"

    # Schedule verification at 4 AM with offset
    local verify_hour=4
    local verify_min=$((verify_offset * 15))
    if [[ $verify_min -ge 60 ]]; then
      verify_hour=$((verify_hour + verify_min / 60))
      verify_min=$((verify_min % 60))
    fi
    local verify_schedule=$(printf "daily %02d:%02d" $verify_hour $verify_min)

    log "Creating verification job for $datastore_name at $verify_schedule"

    # Note: This requires PBS API or manual configuration via web UI
    # For now, log the recommended settings
    log "  Recommended verification schedule: $verify_schedule"
    log "  Verification mode: Full (all backups)"

    ((verify_offset++))
  done
}

display_client_config() {
  log "==================================================================="
  log "PBS Datastore Setup Complete!"
  log "==================================================================="
  log ""
  log "Created Datastores:"
  log "-------------------"

  for hostname in "${!HOSTS[@]}"; do
    log "  - remote-$hostname (for ${HOSTS[$hostname]})"
  done

  log ""
  log "Backup User: backup@pbs"
  log "API Token: $(cat /root/pbs-api-token.txt 2>/dev/null || echo 'See /root/pbs-api-token.txt')"
  log ""
  log "Client Configuration (for each remote host):"
  log "---------------------------------------------"
  log ""

  local pbs_server_ip=$(ip -4 addr show tailscale0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}')
  local pbs_fingerprint=$(proxmox-backup-manager cert info 2>/dev/null | grep -oP '(?<=Fingerprint \(sha256\): )[a-f0-9:]+' | head -1 || echo "RUN: proxmox-backup-manager cert info")

  for hostname in "${!HOSTS[@]}"; do
    log "For $hostname (${HOSTS[$hostname]}):"
    log ""
    log "1. Add PBS storage to Proxmox:"
    log "   pvesm add pbs remote-pbs-aglsrv1 \\"
    log "     --server $pbs_server_ip \\"
    log "     --datastore remote-$hostname \\"
    log "     --username backup@pbs \\"
    log "     --password <API_TOKEN_SECRET> \\"
    log "     --fingerprint $pbs_fingerprint"
    log ""
    log "2. Or via web UI:"
    log "   Datacenter > Storage > Add > PBS"
    log "   - ID: remote-pbs-aglsrv1"
    log "   - Server: $pbs_server_ip"
    log "   - Username: backup@pbs"
    log "   - Password: <API_TOKEN_SECRET>"
    log "   - Datastore: remote-$hostname"
    log "   - Fingerprint: $pbs_fingerprint"
    log ""
  done

  log "==================================================================="
  log ""
  log "Next Steps:"
  log "1. Configure backup jobs on each remote host"
  log "2. Test backup and restore operations"
  log "3. Monitor backup status in PBS web UI"
  log "4. Review and adjust retention policies as needed"
  log ""
  log "==================================================================="
}

# ============================================================================
# Main Execution
# ============================================================================

main() {
  log "Starting PBS datastore setup for AGLSRV1..."

  check_prerequisites
  create_datastore_directories
  create_pbs_datastores
  create_backup_user
  configure_datastore_permissions
  configure_retention_policy
  enable_verification_jobs
  display_client_config

  log "PBS datastore setup completed successfully!"
}

main "$@"
